StoreSample/Controllers/PaymentController.cs
namespace StoreSample.Controllers
{
    using StoreSample.DomainEntities;
    using StoreSample.Models;
    using StoreSample.ServiceInterfaces;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    public class PaymentController : Controller
    {
        private readonly IOrderService orderService;

        public PaymentController(IOrderService orderService)
        {
            this.orderService = orderService;
        }

        private List<OrderViewModel> ShoppingCard
        {
            get
            {
                return this.Session["ShoppingCard"] as List<OrderViewModel> ?? new List<OrderViewModel>();
            }
        }

        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Index(Order model)
        {
            if (!this.ShoppingCard.Any())
            {
                this.ModelState.AddModelError(string.Empty, "Shopping card is empty.");
            }

            if (!this.ModelState.IsValid)
            {
                return View();
            }

            model.Products = this.ShoppingCard
                .Select(p => new OrderProduct { ProductId = p.Product.Id, Quantity = p.Quantity })
                .ToList();

            await this.orderService.AddOrderAsync(model);
            this.Session.Remove("ShoppingCard");
            return this.RedirectToAction("Index", "Home");
        }
    }
}

StoreSample/Controllers/ShoppingCardController.cs
namespace StoreSample.Controllers
{
    using StoreSample.Models;
    using StoreSample.ServiceInterfaces;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using System.Web.Mvc;

    public class ShoppingCardController : Controller
    {
        private readonly IProductService productService;

        public ShoppingCardController(IProductService productService)
        {
            this.productService = productService;
        }

        private List<OrderViewModel> ShoppingCard
        {
            get
            {
                return this.Session["ShoppingCard"] as List<OrderViewModel> ?? new List<OrderViewModel>();
            }

            set
            {
                this.Session["ShoppingCard"] = value;
            }
        }

        public ActionResult Index()
        {
            return this.View(this.ShoppingCard);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> AddToCard(int productId, int quantity)
        {
            var card = this.ShoppingCard;
            card.Add(new OrderViewModel
            {
                Product = await this.productService.GetProductAsync(productId),
                Quantity = quantity
            });

            this.ShoppingCard = card;
            return this.RedirectToAction("Index");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult RemoveFromCard(int productId)
        {
            var card = this.ShoppingCard;
            card = card.Where(c => c.Product.Id != productId).ToList();
            this.ShoppingCard = card;
            return this.RedirectToAction("Index");
        }
    }
}

StoreSample/Views/ShoppingCard/Index.cshtml
@model IEnumerable<StoreSample.Models.OrderViewModel>
@{
    ViewBag.Title = "Shopping Cart";
}

<h2>Shopping Cart</h2>

<div style="font-weight:bold;" class="row">
    <div class="col-md-2">
        Name
    </div>
    <div class="col-md-2">
        Price
    </div>
    <div class="col-md-2">
        Quantity
    </div>
    <div class="col-md-2">
        Action
    </div>
</div>
@foreach (var item in Model)
{
    <div class="row">
        <div class="col-md-2">
            @Html.ActionLink(item.Product.Name, "ProductDetails", "Home", new { id = item.Product.Id }, null)
        </div>
        <div class="col-md-2">
            @item.Product.Price
        </div>
        <div class="col-md-2">
            @item.Quantity
        </div>
        <div class="col-md-2">
            @using (Html.BeginForm("RemoveFromCard", null))
            {
                @Html.AntiForgeryToken()
                <input type="hidden" name="productId" value="@item.Product.Id" />
                <input type="button" data-validate="true" value="Remove" class="btn btn-primary" />
            }
        </div>
    </div>
}

@if (Model.Any())
{
    <div class="row">
        <div class="col-md-2 col-md-offset-6">
            @Model.Sum(o => o.Product.Price * o.Quantity)
        </div>
    </div>
    <div class="row">
        <div class="col-md-2 col-md-offset-6">
            @Html.ActionLink("Checkout", "Index", "Payment")
        </div>
    </div>
}
else
{
    <div class="row">
        <div class="col-md-2 col-md-offset-6">
            @Html.ActionLink("Back to Products", "Index", "Home")
        </div>
    </div>
}